### ISSUE TITLE
Game crash when trying to craft by selecting an item in the Queue Tab

### ISSUE THREAD

**Issue by xcomalien** [Haselnussbomber/LeveHelper#4] opened 2023-05-26 11:00 UTC
When I try to craft an item for an active leve I would go to the Queue tab and click on the item itself.
This would have openened the craft menu straight on the item to be crafted.

Since 6.4 this has been crashing the game.
I'm not sure if this is a Dalamud library issue or from LH but i'm posting here for a bit of visibility.

Here is the Dalamud Crash log. 
[dalamud_appcrash_20230526_130942_337_15460.log](https://github.com/Haselnussbomber/LeveHelper/files/11574474/dalamud_appcrash_20230526_130942_337_15460.log)

**Comment by Haselnussbomber** [comment] 2023-05-26 11:15
Thanks for reporting. I just woke up and will update it soon.

Explanation: The problem is that the AgentIds have shifted and when the C# compiler compiles the code, it doesn’t use a reference by name for an enum anymore, but replaces it with the value. That means even if the enum was updated in ClientStructs (which is shipped with Dalamud), it still uses the wrong Id in the compiled LeveHelper.dll. I just have to recompile it. 🙄

**Comment by Haselnussbomber** [comment] 2023-05-26 11:49
Fixed with [v2.0.3](https://github.com/Haselnussbomber/LeveHelper/releases/tag/v2.0.3). 🙂

**Closed as completed by Haselnussbomber** 2023-05-26 11:49 UTC

**Comment by xcomalien** [comment] 2023-05-26 13:29
I can confirm that the fix works. 

Thank you very much for the work <3
